version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - node
  node:
    image: node:latest
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
